# permissions for end users to edit horizons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: horizon-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: horizon-operator
    app.kubernetes.io/part-of: horizon-operator
    app.kubernetes.io/managed-by: kustomize
  name: horizon-editor-role
rules:
- apiGroups:
  - horizon.openstack.org
  resources:
  - horizons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - horizon.openstack.org
  resources:
  - horizons/status
  verbs:
  - get
