---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - horizon.openstack.org
  resources:
  - horizons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - horizon.openstack.org
  resources:
  - horizons/finalizers
  verbs:
  - update
- apiGroups:
  - horizon.openstack.org
  resources:
  - horizons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
