apiVersion: horizon.openstack.org/v1alpha1
kind: Horizon
metadata:
  name: horizon
spec:
  replicas: 1
  secret: "osp-secret"
  horizonSecret: "blahSecret"
  customServiceConfig: |
    [DEFAULT]
    debug = true

