apiVersion: horizon.openstack.org/v1beta1
kind: Horizon
metadata:
  name: horizon
spec:
  replicas: 1
  secret: "osp-secret"
  customServiceConfig: |
    DEBUG = True
    LOGGING['handlers']['console']['level'] = 'DEBUG'
